//!
//! This code was generated by a tool.
//!
//!
//!   bebopc version:
//!       0.0.1-20210722-1755
//!
//!
//!   bebopc source:
//!       https://github.com/RainwayApp/bebop
//!
//!
//! Changes to this file may cause incorrect behavior and will be lost if
//! the code is regenerated.
//!

use bebop::{Record as _, SubRecord as _};

pub const P_CASE: u8 = 0x12;
pub const EXAMPLE_CONST_INT32: i32 = -123;
pub const EXAMPLE_CONST_UINT64: u64 = 0x123ffffffff;
pub const EXAMPLE_CONST_FLOAT64: f64 = 123.45678e9;
pub const EXAMPLE_CONST_INF: f64 = f64::INFINITY;
pub const EXAMPLE_CONST_NEG_INF: f64 = f64::NEG_INFINITY;
pub const EXAMPLE_CONST_NAN: f64 = f64::NAN;
pub const EXAMPLE_CONST_FALSE: bool = false;
pub const EXAMPLE_CONST_TRUE: bool = true;
pub const EXAMPLE_CONST_STRING: &str = r#"hello "world"
with newlines"#;
pub const EXAMPLE_CONST_GUID: bebop::Guid = bebop::Guid::from_be_bytes([0xe2,0x15,0xa9,0x46,0xb2,0x6f,0x45,0x67,0xa2,0x76,0x13,0x13,0x6f,0x0a,0x17,0x08,]);
