// unset

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.NetworkInformation;
using System.Reflection;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.RegularExpressions;
using Core.Meta;
using Core.Meta.Attributes;
using Core.Meta.Extensions;
using Core.Meta.Interfaces;

namespace Core.Generators.Rust
{
    enum OwnershipType
    {
        Borrowed,
        Owned,
        Constant,
    }

    public class RustGenerator : BaseGenerator
    {
        const int _tab = 4;

        private static readonly string[] _reservedWordsArray =
        {
            "Self", "abstract", "as", "bebop", "become", "box", "break", "const", "continue", "crate", "do", "else",
            "enum", "extern", "false", "final", "fn", "for", "if", "impl", "in", "let", "loop", "macro", "match",
            "mod", "move", "mut", "override", "priv", "pub", "ref", "return", "self", "static", "std", "struct",
            "super", "trait", "true", "try", "type", "typeof", "unsafe", "unsized", "use", "virtual", "where",
            "while", "yield",
        };

        private static readonly HashSet<string> _reservedWords = RustGenerator._reservedWordsArray.ToHashSet();

        public RustGenerator(ISchema schema) : base(schema) { }

        public override string Compile(Version? languageVersion)
        {
            var builder = new IndentedStringBuilder()
                .AppendLine(GeneratorUtils.GetMarkdownAutoGeneratedNotice())
                .AppendLine()
                .AppendLine("use bebop::{Record as _, SubRecord as _};")
                .AppendLine();

            // TODO: do we need to do something with the namespace? Probably not since the file is itself a module.

            foreach (var definition in Schema.Definitions.Values)
            {
                WriteDocumentation(builder, definition.Documentation);
                switch (definition)
                {
                    case ConstDefinition cd:
                        WriteConstDefinition(builder, cd);
                        break;
                    case EnumDefinition ed:
                        WriteEnumDefinition(builder, ed);
                        break;
                    // case MessageDefinition md:
                    //     throw new NotImplementedException();
                    //     break;
                    // case StructDefinition sd:
                    //     throw new NotImplementedException();
                    //     break;
                    // case FieldsDefinition fd:
                    //     throw new NotImplementedException();
                    //     break;
                    // case UnionDefinition ud:
                    //     throw new NotImplementedException();
                    //     break;
                    // case TopLevelDefinition tld:
                    //     throw new NotImplementedException();
                    //     break;
                    default:
                        throw new InvalidOperationException($"unsupported definition {definition.GetType()}");
                        break;
                }

                builder.AppendLine();
            }

            return builder.ToString();
        }

        public override void WriteAuxiliaryFiles(string outputPath)
        {
            // Nothing to do because the runtime is a cargo package.
        }

        private static void WriteConstDefinition(IndentedStringBuilder builder, ConstDefinition d)
        {
            builder.AppendLine(
                $"pub const {MakeConstIdent(d.Name)}: {TypeName(d.Value.Type, OwnershipType.Constant)} = {EmitLiteral(d.Value)};");
        }

        private void WriteEnumDefinition(IndentedStringBuilder builder, EnumDefinition d)
        {
            // main definition
            var name = MakeDefIdent(d.Name);
            builder
                .AppendLine("#[repr(u32)]")
                .AppendLine("#[derive(Copy, Clone, Debug, Eq, PartialEq)]")
                .CodeBlock($"pub enum {name}", _tab, () =>
                {
                    foreach (var m in d.Members)
                    {
                        WriteDocumentation(builder, d.Documentation);
                        WriteDeprecation(builder, m.DeprecatedAttribute);
                        builder.AppendLine($"{MakeEnumVariantIdent(m.Name)} = {m.ConstantValue},");
                    }
                }).AppendLine();

            // conversion from int
            builder.CodeBlock($"impl core::convert::TryFrom<u32> for {name}", _tab, () =>
            {
                builder.AppendLine("type Error = bebop::DeserializeError;")
                    .AppendLine()
                    .CodeBlock("fn try_from(value: u32) -> bebop::DeResult<Self>", _tab, () =>
                    {
                        builder.CodeBlock("match value", _tab, () =>
                        {
                            foreach (var m in d.Members)
                            {
                                builder.AppendLine($"{m.ConstantValue} => Ok({name}::{MakeEnumVariantIdent(m.Name)}),");
                            }

                            builder.AppendLine("d => Err(bebop::DeserializeError::InvalidEnumDiscriminator(d)),");
                        });
                    });
            }).AppendLine();

            // conversion to int
            builder.CodeBlock($"impl core::convert::From<{name}> for u32", _tab, () =>
            {
                builder.CodeBlock($"fn from(value: {name}) -> Self", _tab, () =>
                {
                    builder.CodeBlock("match value", _tab, () =>
                    {
                        foreach (var m in d.Members)
                        {
                            builder.AppendLine($"{name}::{m.Name} => {m.ConstantValue},");
                        }
                    });
                });
            }).AppendLine();

            // sub record
            builder.CodeBlock($"impl<'raw> bebop::SubRecord<'raw> for {name}", _tab, () =>
            {
                builder
                    .AppendLine("const MIN_SERIALIZED_SIZE: usize = bebop::ENUM_SIZE")
                    .AppendLine()
                    .AppendLine("#[inline]")
                    .CodeBlock("fn serialize<W: std::io::Write>(&self, dest: &mut W) -> bebop::SeResult<usize>", _tab,
                        () =>
                        {
                            builder.AppendLine("u32::from(*self).serialize(dest)");
                        })
                    .AppendLine()
                    .AppendLine("#[inline]")
                    .CodeBlock("fn deserialize_chained(raw: &'raw [u8]) -> DeResult<(usize, Self)>", _tab, () =>
                    {
                        builder
                            .AppendLine("let (n, v) = u32::deserialize_chained(raw)?;")
                            .AppendLine("Ok((n, v.try_into()?))");
                    });
            });

            // record
            builder.AppendLine($"impl<'raw> Record<'raw> for {name} {{}}");
        }

        /// <summary>
        /// Generate a Rust type name for the given <see cref="TypeBase"/>.
        /// </summary>
        /// <param name="type">The field type to generate code for.</param>
        /// <param name="ot">Ownership type, e.g. <c>&'raw str</c> versus <c>String</c>.</param>
        /// <returns>The Rust type name.</returns>
        private static string TypeName(in TypeBase type, OwnershipType ot = OwnershipType.Borrowed)
        {
            switch (type)
            {
                case ScalarType st:
                    return st.BaseType switch
                    {
                        BaseType.Bool => "bool",
                        BaseType.Byte => "u8",
                        BaseType.UInt16 => "u16",
                        BaseType.Int16 => "i16",
                        BaseType.UInt32 => "u32",
                        BaseType.Int32 => "i32",
                        BaseType.UInt64 => "u64",
                        BaseType.Int64 => "i64",
                        BaseType.Float32 => "f32",
                        BaseType.Float64 => "f64",
                        BaseType.String => ot switch
                        {
                            OwnershipType.Borrowed => "&'raw str",
                            OwnershipType.Constant => "&str",
                            OwnershipType.Owned => "String",
                            _ => throw new ArgumentOutOfRangeException(nameof(ot))
                        },
                        BaseType.Guid => "bebop::Guid",
                        BaseType.Date => "bebop::Date",
                        _ => throw new ArgumentOutOfRangeException(st.BaseType.ToString())
                    };
                case ArrayType at:
                    if (ot is OwnershipType.Borrowed or OwnershipType.Constant && at.MemberType is ScalarType)
                    {
                        var lifetime = ot is OwnershipType.Borrowed ? "'raw" : "'static";
                        return at.IsOneByteUnits()
                            ? $"&{lifetime} [{TypeName(at.MemberType)}]"
                            : $"bebop::PrimitiveMultiByteArray<{lifetime}, {TypeName(at.MemberType)}>";
                    }
                    else
                    {
                        return $"std::vec::Vec<{TypeName(at.MemberType)}>";
                    }
                case MapType mt:
                    return $"std::collections::HashMap<{TypeName(mt.KeyType)}, {TypeName(mt.ValueType)}>";
                case DefinedType dt:
                    return dt.Name;
            }

            throw new InvalidOperationException($"GetTypeName: {type}");
        }

        private static void WriteDocumentation(IndentedStringBuilder builder, string documentation)
        {
            if (string.IsNullOrEmpty(documentation)) { return; }

            foreach (var line in documentation.GetLines())
            {
                // TODO: make the docs more friendly to rustdoc by formatting as markdown
                builder.AppendLine($"/// {line}");
            }
        }

        private static void WriteDeprecation(IndentedStringBuilder builder, BaseAttribute? attr)
        {
            if (attr is null) { return; }

            builder.Append("#[deprecated");
            if (!string.IsNullOrEmpty(attr.Value))
            {
                builder.AppendMid($"(note = \"{attr.Value}\")");
            }

            builder.AppendEnd("]");
        }

        private static string MakeConstIdent(string ident)
        {
            var reCased = ident.ToSnakeCase().ToUpper();
            return _reservedWords.Contains(reCased)
                ? $"_{reCased}"
                : reCased;
        }

        private string MakeEnumVariantIdent(string ident) => MakeDefIdent(ident);

        private static string MakeDefIdent(string ident)
        {
            var reCased = ident.ToPascalCase();
            return _reservedWords.Contains(reCased)
                ? $"_{reCased}"
                : reCased;
        }

        private static string MakeAttrIdent(string ident)
        {
            var reCased = ident.ToSnakeCase();
            return _reservedWords.Contains(reCased)
                ? $"_{reCased}"
                : reCased;
        }

        private static string MakeStringLiteral(string value) =>
            // rust accepts full UTF-8 strings in code AND even supports newlines
            value.Contains("\"#") ? value.Replace("\\", "\\\\").Replace("\"", "\\\"") : $"r#\"{value}\"#";

        private static string MakeGuidLiteral(Guid guid)
        {
            var g = guid.ToString("N").ToCharArray();
            var builder = new StringBuilder();
            builder.Append("bebop::Guid::from_be_bytes([");
            for (var i = 0; i < g.Length; i += 2)
            {
                builder.Append("0x")
                    .Append(g[i])
                    .Append(g[i + 1])
                    .Append(',');
            }

            builder.Append("])");
            return builder.ToString();
        }

        private static string EmitLiteral(Literal literal) =>
            literal switch
            {
                BoolLiteral bl => bl.Value ? "true" : "false",
                IntegerLiteral il => il.Value,
                FloatLiteral {Value: "inf"} => $"{TypeName(literal.Type)}::INFINITY",
                FloatLiteral {Value: "-inf"} => $"{TypeName(literal.Type)}::NEG_INFINITY",
                FloatLiteral {Value: "nan"} => $"{TypeName(literal.Type)}::NAN",
                FloatLiteral fl => fl.Value.Contains('.') ? fl.Value : fl.Value + '.',
                StringLiteral sl => MakeStringLiteral(sl.Value),
                GuidLiteral gl => MakeGuidLiteral(gl.Value),
                _ => throw new ArgumentOutOfRangeException(literal.ToString()),
            };
    }
}