using System;
using System.Diagnostics.CodeAnalysis;

namespace Bebop.Attributes
{
    /// <summary>
    /// Classes generated by bebopc are marked with this attribute. 
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Enum, Inherited = false)]
    public class BebopRecordAttribute : Attribute
    {
    }
}