using System;
using Bebop.Runtime;

namespace Bebop.Attributes
{
    /// <summary>
    /// Classes generated by bebopc are marked with this attribute.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Enum, Inherited = false)]
    public class BebopRecordAttribute : Attribute
    {
        /// <summary>
        /// Creates a new <see cref="BebopRecord"/> attribute.
        /// </summary>
        /// <param name="kind">The kind of the decorated type.</param>
        /// <param name="isMutable">Whether or not the type record is mutable.</param>
        public BebopRecordAttribute(BebopKind kind, bool isMutable = false)
        {
            Kind = kind;
            IsMutable = isMutable;
        }

        /// <summary>
        /// Indicates if the decorated type is mutable.
        /// </summary>
        public bool IsMutable { get; set; }

        /// <summary>
        /// Indicates the kind of the decorated type.
        /// </summary>
        public BebopKind Kind { get; set; }
    }
}