using System;
using JetBrains.Annotations;

namespace Bebop.Attributes
{
    /// <summary>
    /// Classes generated by bebopc are marked with this attribute. 
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Enum, Inherited = false)]
    [MeansImplicitUse]
    public class BebopRecordAttribute : Attribute
    {
    }
}