//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core.Meta
{

    /// <summary>
    /// A static class to access version information about the Bebop compiler during runtime.
    /// </summary>
    /// <remarks>
    /// This class is populated during the build process.
    /// </remarks>
    public static class VersionInfo
    {
        /// <summary>
        /// The MAJOR version of bebopc.
        /// </summary>
        public const byte Major = 0;
        /// <summary>
        /// The MINOR version of bebopc.
        /// </summary>
        public const byte Minor = 0;
        /// <summary>
        /// The PATCH version of bebopc.
        /// </summary>
        public const byte Patch = 1;
        /// <summary>
        /// The human readable version which may contain additional labels.
        /// </summary>
        public const string Informational = "0.0.1-20210526-1755";
    }
}
